name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "cmdline-tools;latest" "platforms;android-34" "build-tools;34.0.0"

      - name: Unzip project
        run: unzip TaskFlow-Android-v2.zip -d .

      - name: Download Gradle
        run: |
          curl -L https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip

      - name: Build debug APK
        working-directory: TaskFlow
        run: ./gradle-8.7/bin/gradle :app:assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TaskFlow-debug
          path: TaskFlow/app/build/outputs/apk/debug/app-debug.apk
