name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses and Install Build Tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Unzip project
        run: unzip TaskFlow-Android-v2.zip -d .

      - name: Download Gradle
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "PATH=$PWD/gradle-8.7/bin:$PATH" >> $GITHUB_ENV

      - name: Build Debug APK
        working-directory: TaskFlow
        run: gradle :app:assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TaskFlow-debug
          path: TaskFlow/app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1-debug-${{ github.run_number }}
          name: TaskFlow Debug ${{ github.run_number }}
          draft: false
          prerelease: true
          files: TaskFlow/app/build/outputs/apk/debug/app-debug.apk

